### ISSUE TITLE
Figure out whether JSON Schema for PHP can be bundled

### ISSUE THREAD

**Issue by waldoj** [TrustTheVote-Project/horatio-server#28]
It uses [the BSD 2-clause license](https://github.com/justinrainbow/json-schema/blob/master/LICENSE). I don't have the foggiest idea of whether that's compatible with the OSET license. If not, then we can't include it, and it's necessary for folks to install it themselves. :(

**Comment by waldoj** [comment]
@ejohnsebes, is this something that somebody from your team can weigh in on?

**Comment by copiesofcopies** [comment]
BSD 2-clause is compatible with essentially anything, including just about any proprietary license you can throw at it. It is definitely compatible with the OSET license.

**Comment by waldoj** [comment]
Yay! Thank you, @copiesofcopies.
