### ISSUE TITLE
On the README, list that this is legal.

### ISSUE THREAD

**Issue by jvanasco** [TrustTheVote-Project/horatio-server#60]
I couldn't believe that VA allows applications submitted by email.  The state's form/instructions downplays this (while stressing all the walkin/usps info), though it mentions in passing.

It would be great if the README noted whatever laws or court decisions that legitimize this application process.

**Comment by waldoj** [comment]
A fine idea that I only just now got around to acting on. :) Thanks, @jvanasco!

**Comment by jvanasco** [comment]
Thanks!  My friend Debra runs LongDistanceVoter.org so I've seen a lot of political tech stuff over the years.  I was really worried this was illegal (and applications would be thrown out) until someone pointed out who was behind this project.

**Comment by waldoj** [comment]
This project only exists because the state OK'd it. :)

**Comment by trustthevote** [comment]
Jonathan,
Thanks for the good suggestion, and pleased to e-meet you. I'm a fan of 
Debra and LDV too.
Waldo and company did in fact do the legal homework, but you're right in 
pointing out that it's important for that info to go in the repo!
Cheers,
John Sebes

Jonathan Vanasco wrote:

**Comment by jvanasco** [comment]
Sorry, I should have been more clear.  I've long known that this project was legit -- I was primarily worried about someone in another state saying "wow this is awesome!", then forking it for a state where it's not legal.
